# Numpy

Class Notes for I399

### Intrinsic NumPy array creation functions
```Using np.arange (over a range)
np.arange(start,stop,step,dtype=None)
np.arange(5)
np.arange(2, 10, dtype=float)
np.arange(0, 1, 0.1)



Using np.linspace (between two values)
np.linspace(start,stop,num,endpoint=True, dtype=None)
np.linspace(0., 3., 6)
np.linspace(0, 10, 5)
```

In [15]:
import numpy as np

In [16]:
arr1 = np.array([1, 2, 3])
arr1.shape

(3,)

In [17]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2.shape

(2, 3)

In [31]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3.shape

(2, 2, 3)

In [35]:
arr4 = arr3.flatten()
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Insight

np.array.shape:
    will list the length of each dimensinon of an array

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(2,10,dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
np.arange(0,1,dtype=float, step=.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [22]:
np.linspace(0.,3.,6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. ])

In [36]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Intrinsic NumPy array creation functions
Using np.zeros, np.ones, np.eye, and np.indices
```
numpy.zeros(shape, dtype=float, order='C')
np.zeros((4, 3, 2))

numpy.ones(shape, dtype=None, order='C')
np.ones((2, 3))

numpy.eye(N, M=None, k=0, dtype=float, order='C') N: Number of rows, M: Number of columns, optional, k: Index of the diagonal, optional.
    np.eye(5)

np.indices((3, 2, 4))

 Using random Module
from numpy.random import default_rng
default_rng(42).random((2,3))

42 is the seed, so you can regenerate the same pseudorandom numbers.
```

In [41]:
np.zeros((4,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.indices((2,3))

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [48]:
tempshape = (3,2,4)
np.ones(tempshape)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [49]:
np.indices(tempshape)

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2]]],


       [[[0, 0, 0, 0],
         [1, 1, 1, 1]],

        [[0, 0, 0, 0],
         [1, 1, 1, 1]],

        [[0, 0, 0, 0],
         [1, 1, 1, 1]]],


       [[[0, 1, 2, 3],
         [0, 1, 2, 3]],

        [[0, 1, 2, 3],
         [0, 1, 2, 3]],

        [[0, 1, 2, 3],
         [0, 1, 2, 3]]]])

In [53]:
from numpy.random import default_rng as rng
#This is a guess, but I think rng stands for:
# Random Range

In [72]:
seed = 42
print("Seeded Random:")
print(rng(seed).random((2,3)))

for i in range (6):
    print(f"\nRandom {i}:")
    print(rng().random((2,3)))

Seeded Random:
[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]

Random 0:
[[0.19700189 0.20893524 0.98042499]
 [0.2282269  0.96083128 0.80666106]]

Random 1:
[[0.4993475  0.98061599 0.71721732]
 [0.24012294 0.13801734 0.40449069]]

Random 2:
[[0.0293155  0.73008008 0.80529119]
 [0.01380751 0.88891277 0.81986996]]

Random 3:
[[0.35529074 0.77501877 0.29300106]
 [0.60869904 0.00697018 0.38089922]]

Random 4:
[[0.84549001 0.51890504 0.5537218 ]
 [0.43486935 0.73406835 0.62242856]]

Random 5:
[[0.68345954 0.85313891 0.75108722]
 [0.54864408 0.53009157 0.16035991]]
